# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoquiz', '0003_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoquiz.Country')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoquiz.Quiz')),
            ],
        ),
    ]
