# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoquiz', '0004_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='continent',
            new_name='region',
        ),
    ]
